SET(MATLAB_FOUND 0)

MESSAGE(STATUS "Searching for Matlab")

IF(WIN32)
        
        SET(CMAKE_PROGRAM_PATH
                "[HKEY_LOCAL_MACHINE\\SOFTWARE\\MATLAB\\R2009b;MATLABROOT]/bin"
        )
        
        SET(CMAKE_LIBRARY_PATH 
                "[HKEY_LOCAL_MACHINE\\SOFTWARE\\MATLAB\\R2009b;MATLABROOT]/extern/lib/win32/microsoft"
        )
        
        FIND_PATH(MATLAB_INCLUDE_DIR
                "mex.h"
                "[HKEY_LOCAL_MACHINE\\SOFTWARE\\MATLAB\\R2009b;MATLABROOT]/extern/include"
        )
        
        SET (CMAKE_FIND_LIBRARY_PREFIXES "lib")
        
ELSE(WIN32)

  IF(APPLE)

    FIND_PROGRAM(MATLAB_MEXEXT mexext) 
    GET_FILENAME_COMPONENT(CMAKE_PROGRAM_PATH 
                ${MATLAB_MEXEXT} PATH)

    SET(CMAKE_LIBRARY_PATH
        "${CMAKE_PROGRAM_PATH}/maci64/"
    )
    
    FIND_PATH(MATLAB_INCLUDE_DIR
            "mex.h"
        "${CMAKE_PROGRAM_PATH}/../extern/include/"
    )

  ELSE(APPLE)

    FIND_PROGRAM(MATLAB_MEXEXT mexext) 
    GET_FILENAME_COMPONENT(CMAKE_PROGRAM_PATH 
                ${MATLAB_MEXEXT} PATH)

    SET(CMAKE_LIBRARY_PATH
        "${CMAKE_PROGRAM_PATH}/glnxa64/"
    )
    
    FIND_PATH(MATLAB_INCLUDE_DIR
            "mex.h"
        "${CMAKE_PROGRAM_PATH}/../extern/include/"
    )

  ENDIF(APPLE)

ENDIF(WIN32)

# This is common to UNIX and Win32:

FIND_PROGRAM(MATLAB_MEX_EXECUTABLE
        mex
        NO_CMAKE_ENVIRONMENT_PATH
)
FIND_PROGRAM(MATLAB_MEXEXT_EXECUTABLE
        mexext
        NO_CMAKE_ENVIRONMENT_PATH
)
FIND_LIBRARY(MATLAB_MEX_LIBRARY
        mex
        NO_CMAKE_ENVIRONMENT_PATH
)
FIND_LIBRARY(MATLAB_MX_LIBRARY
        mx
        NO_CMAKE_ENVIRONMENT_PATH
)
FIND_LIBRARY(MATLAB_MAT_LIBRARY
        mat
        NO_CMAKE_ENVIRONMENT_PATH
)
FIND_LIBRARY(MATLAB_ENG_LIBRARY
        eng
        NO_CMAKE_ENVIRONMENT_PATH
)

SET(MATLAB_LIBRARIES
        ${MATLAB_MEX_LIBRARY}
        ${MATLAB_MX_LIBRARY}
        ${MATLAB_MAT_LIBRARY}
        ${MATLAB_ENG_LIBRARY}
)

execute_process ( COMMAND ${MATLAB_MEXEXT_EXECUTABLE}
                OUTPUT_VARIABLE MATLAB_MEX_EXT
                OUTPUT_STRIP_TRAILING_WHITESPACE)
                
IF(MATLAB_INCLUDE_DIR AND MATLAB_LIBRARIES)
        MESSAGE("-- Matlab binaries: ${CMAKE_PROGRAM_PATH}")
        MESSAGE("-- Matlab libraries: ${CMAKE_LIBRARY_PATH}")
        MESSAGE("-- MEX extension: ${MATLAB_MEX_EXT}")
        SET(MATLAB_FOUND 1)
ENDIF(MATLAB_INCLUDE_DIR AND MATLAB_LIBRARIES)

MARK_AS_ADVANCED(
  MATLAB_LIBRARIES
  MATLAB_MEX_LIBRARY
  MATLAB_MAT_LIBRARY
  MATLAB_MX_LIBRARY
  MATLAB_ENG_LIBRARY
  MATLAB_INCLUDE_DIR
  MATLAB_FOUND
  MATLAB_MEX_EXECUTABLE
  MATLAB_MEXEXT_EXECUTABLE
  MATLAB_MEX_EXT
)
